import Nav from '@/Components/Nav'
import './globals.css'
import { Poppins } from 'next/font/google'
import { SearchProvider } from '@/Context/SearchContext'

const poppins = Poppins(
    { 
      weight : ['100','300','400','500','700','900'],
      subsets: ['latin'] 
    }
  )

export const metadata = {
  title: 'Cars_Hub | Official Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SearchProvider>
            <div className='w-full relative'>
              <Nav />
              {children}
            </div>
        </SearchProvider>
      </body>
    </html>
  )
}
